namespace ExtendedHotkeys.Settings
{
    public enum SettingKey
    {
        DisableMod = 0,
        EnableNetToolWheel = 1,
        EnableElevationWheel = 2,
        EnableSnappingWheel = 3,
        EnableElevationReset = 4,
        ExpandNTMGroup = 5,
        EnableNTMGroup = 5,
        EnableNTMStraight = 6,
        EnableNTMSimpleCurve = 7,
        EnableNTMComplexCurve = 8,
        EnableNTMContinuous = 9,
        EnableNTMGrid = 10,
        EnableAnarchyMode = 11,
        EnableElevationStepScroll = 12,
        EnableNetToolReverse = 13,
        EnableElevationReverse = 14,
        EnableBrushSizeWheel = 15,
        EnableBrushStrengthWheel = 16,
        EnableBrushSizeReverse = 17,
        EnableBrushStrengthReverse = 18,
        ExpandReverseGroup = 19,
        EnableZonesHotkeys = 20,
        EnableElectricityHotkeys = 21,
        EnableWaterAndSewageHotkeys = 22,
        EnableTransportationHotkeys = 23,
        EnableHealthAndDeathcareHotkeys = 24,
        EnableFireAndRescueHotkeys = 25,
        EnableEducationAndResearchHotkeys = 26,
        EnableGarbageManagementHotkeys = 27,
        EnableParksAndRecreationHotkeys = 28,
        EnableCommunicationsHotkeys = 29,
        EnableLandscapingHotkeys = 30,
        EnableRoadsHotkeys = 31,
        EnableSignaturesHotkeys = 32,
        EnableAreasHotkeys = 33,
        EnablePoliceAndAdministrationHotkeys = 34,
        EnableOpenMenus = 35,
        ExpandOpenMenus = 35,
        EnableNetToolHotkeys = 36
    }
}